x-deploy: &deploy-section
  mode: replicated
  replicas: 1
  placement:
    constraints:
      - node.labels.postgres == true
  restart_policy:
    condition: any
    max_attempts: 5
    delay: 5s
    window: 30s
  update_config:
    parallelism: 2
    delay: 5s
    failure_action: rollback
    order: stop-first
  rollback_config:
    parallelism: 2
    delay: 5s
    failure_action: pause
    order: stop-first

x-env: &env-section
  env_file:
    - postgres.env

x-logging: &logging-section
  driver: "json-file"

x-logging-options: &logging-options
  max-size: 10m
  max-file: "3"

version: "3.9"

services:
  postgres:
    image: nexus.kioosk.dev/postgres:13
    ports:
      - 5432:5432
    command: postgres -c 'max_connections=200'
    <<: *env-section
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-initsql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      <<: *deploy-section
    networks:
      production:
        aliases:
          - postgres.postgres
    logging:
      <<: *logging-section
      options:
        <<: *logging-options
        tag: production-postgres_postgres

networks:
  postgres:
    driver: overlay
    attachable: true
    driver_opts:
      com.docker.network.driver.mtu: 1400
    
volumes:
  postgres-data:
  postgres-initsql:
