x-deploy: &deploy-section
  mode: replicated
  replicas: 1
  placement:
    constraints:
      - node.labels.vault == true
  restart_policy:
    condition: any
    max_attempts: 5
    delay: 5s
    window: 30s
  update_config:
    parallelism: 2
    delay: 5s
    failure_action: rollback
    order: stop-first
  rollback_config:
    parallelism: 2
    delay: 5s
    failure_action: pause
    order: stop-first

x-logging: &logging-section
  driver: "json-file"

x-logging-options: &logging-options
  max-size: 10m
  max-file: "3"

version: "3.9"

services:
  vault:
    image: vault 
    ports:
      - 8200:8200
    networks:
      production:
        aliases:
          - swarm.vault  
    volumes:
      - vault-data:/vault/file/
    environment:
      - 'VAULT_LOCAL_CONFIG={"storage": {"file": {"path": "/vault/file"}}, "listener": [{"tcp": { "address": "0.0.0.0:8200", "tls_disable": true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}'
    command: server 
    cap_add:
      - IPC_LOCK

volumes:
  vault-data:

networks:
  swarm:
    external: true
