x-deploy: &deploy-section
  mode: replicated
  replicas: 1
  placement:
    constraints:
      - node.labels.rabbitmq == true
  restart_policy:
    condition: any
    max_attempts: 5
    delay: 5s
    window: 30s
  update_config:
    parallelism: 2
    delay: 5s
    failure_action: rollback
    order: stop-first
  rollback_config:
    parallelism: 2
    delay: 5s
    failure_action: pause
    order: stop-first

x-env: &env-section
  env_file:
    - rabbitmq.env

x-logging: &logging-section
  driver: "json-file"

x-logging-options: &logging-options
  max-size: 10m
  max-file: "3"

version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.8.17-management
    hostname: "rabbitmq"
    ports:
      # - 5672:5672
      - 15672:15672
    <<: *env-section
    deploy:
      <<: *deploy-section
    volumes:
      - rabbitmq-etc:/etc/rabbitmq/
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq/
    networks:
      swarm:
        aliases:
          - swarm.rabbitmq
    logging:
      <<: *logging-section
      options:
        <<: *logging-options
        tag: swarm-rabbitmq_rabbitmq

networks:
  swarm:
    external: true
    
volumes:
  rabbitmq-data:
  rabbitmq-log:
  rabbitmq-etc:
