---
- name: Change Default Route, DNS and HTTP_PROXY
  hosts: servers
  become: yes
  become_user: root
  
  vars_files:
    - vars.yml

  tasks:
    - name: Change default route via {{ route_host }}
      command: ip route change default via {{ route_host }}
      tags:
        - change_route

    - name: Empty the resolv.conf file
      copy:
        content: ""
        dest: /etc/resolv.conf
      tags:
        - change_dns

    - name: Add custom dns in resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver {{ item }}"
        state: present
      with_items: "{{ dns_servers }}"
      tags:
        - change_dns

    - name: Remove dpkg lock file if exists
      command: rm -f /var/lib/apt/lists/lock /var/lib/dpkg/lock-frontend
      ignore_errors: yes
      tags:
        - updateـpackage

    - name: Update package cache
      apt:
        update_cache: yes
      tags:
        - updateـpackage
