x-deploy: &deploy-section
  mode: replicated
  replicas: 1
  restart_policy:
    condition: any
    max_attempts: 5
    delay: 5s
    window: 30s
  update_config:
    parallelism: 2
    delay: 5s
    failure_action: rollback
    order: stop-first
  rollback_config:
    parallelism: 2
    delay: 5s
    failure_action: pause
    order: start-first

x-env: &env-section
  env_file:
    - gitlab.env

x-logging: &logging-section
  driver: "json-file"

x-logging-options: &logging-options
  max-size: 10m
  max-file: "3"

version: '3.9'

services:
   gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: "gitlab"
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    volumes:
      - '/opt/gitlab/config:/etc/gitlab'
      - '/opt/gitlab/logs:/var/log/gitlab'
      - '/opt/gitlab/data:/var/opt/gitlab'
    ports:
      - 2222:22
    <<: *env-section
    networks:
      gitlab:
        aliases:
          - gitlab.gitlab
    deploy:
      <<: *deploy-section
      placement:
        constraints:
          - node.labels.gitlab == true
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    logging:
      <<: *logging-section
      options:
        <<: *logging-options
        tag: gitlab_gitlab

configs:
  gitlab:
    file: config/gitlab.rb

volumes:
  gitlab-data:
  gitlab-config:
  gitlab-runner-config:
  
networks:
  gitlab:
    driver: overlay
    attachable: true
    driver_opts:
      com.docker.network.driver.mtu: 1400
