version: '3.9'

services:
  metabase:
    image: metabase/metabase:v0.48.2
    ports:
      - 3000:3000
    volumes:
      - /dev/urandom:/dev/random:ro
    env_file:
      - metabase.env
    networks:
      - metabase
 
  postgres-metabase:
    image: postgres:15
    env_file:
      - postgres-metabase.env
    volumes:
      - postgres-metabase-data:/var/lib/postgresql/data
      - postgres-metabase-initsql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - metabase
    
networks:
  metabase:

volumes:
  postgres-metabase-data:
  postgres-metabase-initsql:
